# Generated by Django 4.2 on 2023-04-29 12:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0004_candidate_delete_candidateinfo_delete_techskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='tech_skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Ruby', 'Ruby'), ('Docker', 'Docker'), ('Node', 'Node'), ('JS', 'Js')], max_length=255),
        ),
    ]
